// Package generator generates static composition Go code from feature resolutions.
package generator

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/project/mcp-go-core/internal/featuregraph"
)

// Generator interface for code generation.
type Generator interface {
	Generate(ctx context.Context, config Config) error
}

// Config holds generator configuration.
type Config struct {
	OutputDir        string
	Resolution       *featuregraph.Resolution
	FrameworkVersion string
	Modules          []ModuleInfo
}

// ModuleInfo describes a module for code generation.
type ModuleInfo struct {
	Name    string
	Package string
	Import  string
}

// GeneratorImpl implements Generator.
type GeneratorImpl struct{}

// New creates a new Generator.
func New() Generator {
	return &GeneratorImpl{}
}

// Generate generates all static composition files.
func (g *GeneratorImpl) Generate(ctx context.Context, cfg Config) error {
	if err := os.MkdirAll(cfg.OutputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output dir: %w", err)
	}

	if err := g.generateFeatures(cfg); err != nil {
		return err
	}
	if err := g.generateModules(cfg); err != nil {
		return err
	}
	if err := g.generateServer(cfg); err != nil {
		return err
	}
	if err := g.generateRouter(cfg); err != nil {
		return err
	}
	if err := g.generateBuildInfo(cfg); err != nil {
		return err
	}
	if err := g.generateMetadata(cfg); err != nil {
		return err
	}

	return nil
}

// generateFeatures generates features.go with feature flag constants.
func (g *GeneratorImpl) generateFeatures(cfg Config) error {
	var lines []string
	lines = append(lines, "// Code generated by mcp-go-core. DO NOT EDIT.")
	lines = append(lines, "package generated")
	lines = append(lines, "")
	lines = append(lines, "import \"fmt\"")
	lines = append(lines, "")

	enabled := make([]string, len(cfg.Resolution.Enabled))
	copy(enabled, cfg.Resolution.Enabled)
	inferred := make([]string, len(cfg.Resolution.Inferred))
	copy(inferred, cfg.Resolution.Inferred)
	sort.Strings(enabled)
	sort.Strings(inferred)

	allFeatures := append(enabled, inferred...)
	sort.Strings(allFeatures)

	lines = append(lines, "// Feature flags. Use IsFeatureEnabled() to check.")
	lines = append(lines, "var features = map[string]bool{")
	for _, f := range allFeatures {
		lines = append(lines, fmt.Sprintf("\t\"%s\": true,", f))
	}
	lines = append(lines, "}")
	lines = append(lines, "")
	lines = append(lines, "// IsFeatureEnabled checks if a feature is enabled.")
	lines = append(lines, "func IsFeatureEnabled(name string) bool {")
	lines = append(lines, "\treturn features[name]")
	lines = append(lines, "}")
	lines = append(lines, "")

	// Feature constants
	lines = append(lines, "// Feature constants.")
	for _, f := range allFeatures {
		constant := toConstantName(f)
		lines = append(lines, fmt.Sprintf("const Feature%s = \"%s\"", constant, f))
	}

	return os.WriteFile(filepath.Join(cfg.OutputDir, "features.go"), []byte(strings.Join(lines, "\n")), 0644)
}

func toConstantName(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

// generateModules generates modules.go with static module composition.
func (g *GeneratorImpl) generateModules(cfg Config) error {
	var lines []string
	lines = append(lines, "// Code generated by mcp-go-core. DO NOT EDIT.")
	lines = append(lines, "package generated")
	lines = append(lines, "")

	// Only import resolved/enabled modules
	enabledModules := make(map[string]bool)
	for _, mi := range cfg.Modules {
		for _, f := range cfg.Resolution.Enabled {
			if mi.Name == f || strings.HasPrefix(f, strings.Split(mi.Name, "/")[0]) {
				enabledModules[mi.Import] = true
			}
		}
		for _, f := range cfg.Resolution.Inferred {
			if mi.Name == f || strings.HasPrefix(f, strings.Split(mi.Name, "/")[0]) {
				enabledModules[mi.Import] = true
			}
		}
	}

	// Sorted imports
	imports := make([]string, 0, len(enabledModules))
	for imp := range enabledModules {
		imports = append(imports, imp)
	}
	sort.Strings(imports)

	lines = append(lines, "import (")
	for _, imp := range imports {
		lines = append(lines, fmt.Sprintf("\t\"%s\"", imp))
	}
	lines = append(lines, ")")
	lines = append(lines, "")

	// ConfigureAll function that calls individual module Configure
	lines = append(lines, "// ConfigureAll configures all enabled modules.")
	lines = append(lines, "// This function calls each module's Configure directly,")
	lines = append(lines, "// NOT modules/all.")
	lines = append(lines, "func ConfigureAll() error {")

	// Map module names to import aliases
	for _, mi := range cfg.Modules {
		enabled := false
		for _, f := range cfg.Resolution.Enabled {
			if mi.Name == f || strings.HasPrefix(f, strings.Split(mi.Name, "/")[0]) {
				enabled = true
				break
			}
		}
		if !enabled {
			for _, f := range cfg.Resolution.Inferred {
				if mi.Name == f || strings.HasPrefix(f, strings.Split(mi.Name, "/")[0]) {
					enabled = true
					break
				}
			}
		}
		if enabled {
			alias := toPackageAlias(mi.Import)
			lines = append(lines, fmt.Sprintf("\t%s.Configure()", alias))
		}
	}

	lines = append(lines, "\treturn nil")
	lines = append(lines, "}")
	lines = append(lines, "")

	return os.WriteFile(filepath.Join(cfg.OutputDir, "modules.go"), []byte(strings.Join(lines, "\n")), 0644)
}

func toPackageAlias(importPath string) string {
	parts := strings.Split(importPath, "/")
	if len(parts) == 0 {
		return importPath
	}
	return strings.ReplaceAll(parts[len(parts)-1], "-", "")
}

// generateServer generates server.go bootstrap.
func (g *GeneratorImpl) generateServer(cfg Config) error {
	content := `// Code generated by mcp-go-core. DO NOT EDIT.
package generated

import (
	"context"
	"github.com/project/mcp-go-core/core/server"
	"github.com/project/mcp-go-core/core/protocol"
)

// NewServer creates a fully configured MCP server.
func NewServer(ctx context.Context) (*server.Server, error) {
	srv := server.NewServer()

	// Configure all enabled modules
	if err := ConfigureAll(); err != nil {
		return nil, err
	}

	// Initialize protocol handlers
	_ = protocol.JSONRPCVersion

	return srv, nil
}
`
	return os.WriteFile(filepath.Join(cfg.OutputDir, "server.go"), []byte(content), 0644)
}

// generateRouter generates router.go.
func (g *GeneratorImpl) generateRouter(cfg Config) error {
	content := `// Code generated by mcp-go-core. DO NOT EDIT.
package generated

import (
	"github.com/project/mcp-go-core/core/router"
)

// NewRouter creates a router with all registered tools, resources, and prompts.
func NewRouter() *router.Router {
	return router.NewRouter()
}
`
	return os.WriteFile(filepath.Join(cfg.OutputDir, "router.go"), []byte(content), 0644)
}

// generateBuildInfo generates buildinfo.go.
func (g *GeneratorImpl) generateBuildInfo(cfg Config) error {
	// Compute lock hash
	features := append([]string{}, cfg.Resolution.Enabled...)
	features = append(features, cfg.Resolution.Inferred...)
	sort.Strings(features)

	edges := make([][]string, 0)
	for _, name := range cfg.Resolution.Graph.ListFeatures() {
		f := cfg.Resolution.Graph.GetFeature(name)
		if f == nil {
			continue
		}
		for _, dep := range f.Dependencies {
			edges = append(edges, []string{name, dep.Name})
		}
	}

	hash := featuregraph.ComputeLockHash(features, edges, cfg.Resolution.Profile, cfg.FrameworkVersion)

	now := time.Now().UTC().Format(time.RFC3339)
	gitCommit := "unknown"

	content := fmt.Sprintf(`// Code generated by mcp-go-core. DO NOT EDIT.
package generated

// BuildInfo holds build-time metadata.
var BuildInfo = struct {
	FrameworkVersion string
	Profile          string
	GraphHash        string
	GeneratedAt      string
	GitCommit        string
}{
	FrameworkVersion: "%s",
	Profile:          "%s",
	GraphHash:        "%s",
	GeneratedAt:      "%s",
	GitCommit:        "%s",
}
`, cfg.FrameworkVersion, cfg.Resolution.Profile, hash, now, gitCommit)

	return os.WriteFile(filepath.Join(cfg.OutputDir, "buildinfo.go"), []byte(content), 0644)
}

// generateMetadata generates metadata.json for the analyzer.
func (g *GeneratorImpl) generateMetadata(cfg Config) error {
	features := append([]string{}, cfg.Resolution.Enabled...)
	features = append(features, cfg.Resolution.Inferred...)
	sort.Strings(features)

	modules := make([]string, 0, len(cfg.Modules))
	for _, m := range cfg.Modules {
		modules = append(modules, m.Name)
	}
	sort.Strings(modules)

	data, err := json.MarshalIndent(map[string]any{
		"framework_version": cfg.FrameworkVersion,
		"profile":           cfg.Resolution.Profile,
		"features":          features,
		"modules":           modules,
		"generated_at":      time.Now().UTC().Format(time.RFC3339),
	}, "", "  ")
	if err != nil {
		return err
	}

	metaDir := filepath.Join(cfg.OutputDir, "..", "generated")
	if err := os.MkdirAll(metaDir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(metaDir, "metadata.json"), data, 0644)
}

// Checksum computes a deterministic checksum of the generated output.
func Checksum(cfg Config) (string, error) {
	var buf strings.Builder

	// Sort modules
	modules := make([]ModuleInfo, len(cfg.Modules))
	copy(modules, cfg.Modules)
	sort.Slice(modules, func(i, j int) bool {
		return modules[i].Import < modules[j].Import
	})

	// Write module imports
	for _, m := range modules {
		buf.WriteString(m.Import)
		buf.WriteString("\n")
	}

	// Write enabled features
	features := append([]string{}, cfg.Resolution.Enabled...)
	features = append(features, cfg.Resolution.Inferred...)
	sort.Strings(features)
	for _, f := range features {
		buf.WriteString(f)
		buf.WriteString("\n")
	}

	h := sha256.Sum256([]byte(buf.String()))
	return hex.EncodeToString(h[:]), nil
}
